name: docs

on:
  push:
    branches:
      - main
jobs:
  pages:
    name: "Docs - Github Pages"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      # - name: "Install dependencies"
      #   run: |
      #     python -VV
      #     python -m site
      #     python -m pip install --upgrade pip setuptools wheel
      #     python -m pip install .
      #     python -m pip install mkdocs-material mkdocstrings[python]
      # - run: pip install mkdocs-material mkdocstrings[python]
      # - run: mkdocs gh-deploy --force
